### PR TITLE
Remove VisualBoyAdvance variants

### PR DESCRIPTION
**Pull request by meithecatte**
Apart from its dubious accuracy, VBA is ripe with dangerous vulnerabilities. Considering that an emulator is usually used to open files downloaded from shady sites, it is not responsible to recommend a program with this security posture.

See also:
 - https://github.com/visualboyadvance-m/visualboyadvance-m/issues/784
 - https://www.youtube.com/watch?v=mHSWxxK6nA8

### CODE REVIEW

**Comment by ZachBacon** [comment]
This hasn't been an issue for several years for now with visualboyadvance-m.

**Comment by meithecatte** [comment]
Are you sure? While I'm in no position to investigate this at the moment, at the very least the linked issue is still open...

**Comment by ZachBacon** [comment]
> Are you sure? While I'm in no position to investigate this at the moment, at the very least the linked issue is still open...

Considering I'm on the team, I'll double check, but I'm pretty sure it's been solved.

**Comment by ZachBacon** [comment]
So I was definitely, wrong, I was confusing another issue with another. But I am working on it currently. It may take a little bit. Faced with trying to adapt current code. Or replace the functionality altogether. Both not exactly easy. But I am working on it to resolve the issue.

**Pull request merged**
